---

# Returns:
# * aws_vpc_subnet_vpc_id
# * aws_vpc_subnet_vpc_cidr
- include_tasks: gather_facts.yml

# Now loop over all subnets for the current VPC
- include_tasks: delete_vpc_subnet.yml
  loop_control:
    loop_var: subnet
  with_items:
    - "{{ vpc.subnets }}"
